// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVVZJ5U0IWFXiMipSVWUVZkuPndPTH1w',
    appId: '1:636689377850:web:2ba5cd20e0ea1fef2be303',
    messagingSenderId: '636689377850',
    projectId: 'edumart-fe5db',
    authDomain: 'edumart-fe5db.firebaseapp.com',
    storageBucket: 'edumart-fe5db.firebasestorage.app',
    measurementId: 'G-5P9L6Z5YDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86W1FQhUFk-tE0dY1OtpP-Sz97ImFJ90',
    appId: '1:636689377850:android:0187337a8380c1082be303',
    messagingSenderId: '636689377850',
    projectId: 'edumart-fe5db',
    storageBucket: 'edumart-fe5db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxrY-fjHGnTObcM-vj6sUz1yEiKHU6kpk',
    appId: '1:636689377850:ios:1c6907db35c00c432be303',
    messagingSenderId: '636689377850',
    projectId: 'edumart-fe5db',
    storageBucket: 'edumart-fe5db.firebasestorage.app',
    iosBundleId: 'com.example.eduMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxrY-fjHGnTObcM-vj6sUz1yEiKHU6kpk',
    appId: '1:636689377850:ios:1c6907db35c00c432be303',
    messagingSenderId: '636689377850',
    projectId: 'edumart-fe5db',
    storageBucket: 'edumart-fe5db.firebasestorage.app',
    iosBundleId: 'com.example.eduMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVVZJ5U0IWFXiMipSVWUVZkuPndPTH1w',
    appId: '1:636689377850:web:3e07b359d95233fa2be303',
    messagingSenderId: '636689377850',
    projectId: 'edumart-fe5db',
    authDomain: 'edumart-fe5db.firebaseapp.com',
    storageBucket: 'edumart-fe5db.firebasestorage.app',
    measurementId: 'G-XMEL66710Z',
  );
}
